module.exports = {
  "AVAILABLE_LOCATIONS": [
{city:"Hong Kong",country:"Hong Kong",fact:"last year they had 25587000 visitors!"},
{city:"Singapore",country:"Singapore",fact:"it is the world'\s safest country"},
{city:"Bangkok",country:"Thailand",fact:"Vimanmek Mansion in Bangkok is the world's largest teak building"},
{city:"London",country:"the UK",fact:"London is the best city in the world and home of the Queen"},
{city:"Paris",country:"France",fact:"there is a law in Paris that buildings cannot exceed 6 stories high"},
{city:"Macau",country:"Macau",fact:"the area with all the hotels resorts is actually built over a reclaimed landfill"},
{city:"New York City",country:"America",fact:"Central Park is one of the world’s largest urban parks at 843 acres"},
{city:"Shenzhen",country:"China",fact:"this is surely the fastest growing city ever, there were 100,000 people in 1970 and 14 million people today"},
{city:"Kuala Lumpur",country:"Malaysia",fact:"the airport contains a glass bowl in the middle with a real rainforest in it"},
{city:"Antalya",country:"Turkey",fact:"within the city is a place called Kaleiçi which has buildings dating back to Roman times"},
{city:"Istanbul",country:"Turkey",fact:"it\`s the only city across 2 continents; both Asia and Europe"},
{city:"Dubai",country:"the United Arab Emirates",fact:"it hosts the world\'s tallest building, the Burj Khalifa, which is 2,7222 feet high"},
{city:"Seoul",country:"South Korea",fact:"they have the world's fastest internet speeds and the best 4G availability"},
{city:"Rome",country:"Italy",fact:"the Coliseum can seat 50,000 people and is one of the Seven Wonders of the World"},
{city:"Phuket",country:"Thailand",fact:"Phuket is known for it\'s beaches, with 36 of them in total"},
{city:"Mecca",country:"Saudi Arabia",fact:"the Masjid al Haram is for Muslims the holiest mosque on Earth and strictly off limits to non-Muslims"},
{city:"Pattaya",country:"Thailand",fact:"Pattaya is one of the best diving sites offering clear and good weather all year round; just 30 minutes from the shore, you can visit a number of islands and shipwrecks "},
{city:"Taipei",country:"Taiwan",fact:"the famous Taipei 101 building is the 5th tallest in the world at 1,667 feet"},
{city:"Miami",country:"America",fact:"it\s the only major American city to have been founded by a woman, Julia Tuttle"},
{city:"Prague",country:"Czechia",fact:"the largest castle in the world is the Prague Castle"},
{city:"Shanghai",country:"China",fact:"this city hosts the longest metro system in the world with 400 miles of tunnels and tracks"},
{city:"Las Vegas",country:"America",fact:"at least 150 couples get married every day in Las Vegas"},
{city:"Milan",country:"Italy",fact:"it has the most skyscrapers of any Italian city and the Milan Cathedral is the 5th largest in the world"},
{city:"Barcelona",country:"Spain",fact:"it/'s one of the worst places to drive in the world with an accident occurring every 19 seconds"},
{city:"Moscow",country:"Russia",fact:"it\'s so big it could be a country, with the population of Norway and Switzerland combined"},
{city:"Amsterdam",country:"the Netherlands",fact:"it has more bikes than people, over a million of them"},
{city:"Vienna",country:"Austria",fact:"Vienna is the only capital city in the world to produce significant quantities of wine within city limits"},
{city:"Venice",country:"Italy",fact:"in order to ride a Gondolier you must have a licence and there are only 400 of them available"},
{city:"Los Angeles",country:"America",fact:"the famous Hollywood sign actually used to say 'Hollywoodland' and was an advert for a local real estate company"},
{city:"Tokyo",country:"Japan",fact:"it\'s the most populated city in the world, in 2016 there 38 million people there"},
{city:"Berlin",country:"Germany",fact:"it was the first European city to have traffic lights"},
{city:"Budapest",country:"Hungary",fact:"Budapest was built over thermal springs delivering 70 million litres of free hot water every day"},
{city:"Florence",country:"Italy",fact:"it was the first city in Europe, founded in 1339"},
{city:"Madrid",country:"Spain",fact:"their official symbol is a bear eating berries from a tree; it symbolises growth, ownership and possession of wood"},
{city:"Warsaw",country:"Poland",fact:"it is over 1400 years old"},
{city:"Chennai",country:"India",fact:"Tidel Park in the city is the largest technology park in Asia; it houses the head offices of many big software companies"},
{city:"Mexico City",country:"Mexico",fact:"it\'s built on a lake called Texcoco which is constantly sinking and has sunk more than nine meters over the last 100 years"},
{city:"Dublin",country:"Ireland",fact:"the City of Dublin contains 666 licensed pubs"},
{city:"San Francisco",country:"America",fact:"before it was renamed to San Francisco, this small city was actually called Yerba Buena"},
{city:"Brussels",country:"Belgium",fact:"the city is home to the EU and NATO headquarters, many international organisations and lots of politicians and diplomats"},
{city:"Burgas",country:"Bulgaria",fact:"Burgas is well-know for the Church of Saint Cyril and Methodius which has some very striking stained-glass windows"},
{city:"Munich",country:"Germany",fact:"the oldest building in the city is actually a bathroom"},
{city:"Zhuhai",country:"China",fact:"it\'s located at the south of the Tropic of Cancer with sunshine all year long"},
{city:"Sydney",country:"Australia",fact:"the Sydney Harbour Bridge is the widest long-span bridge and tallest steel arch bridge in the world"},
{city:"Zurich",country:"Switzerland",fact:"this city will never leave you thirsty as there are 1,200 water fountains in the city alone"},
{city:"Frankfurt",country:"Germany",fact:"it has one of the biggest inner-city forests in the world with 5,785 hectares within city limits"},
{city:"Vancouver",country:"Canada",fact:"it has Canada's longest pool, which is 137 metres long or 3 times as long as an Olympic pool and filled with saltwater"},
{city:"Melbourne",country:"Australia",fact:"it isn't the capital of Australia, but it did used to be for 26 years between 1901 and 1927"},
{city:"Amman",country:"Jordan",fact:"the city\'s high altitude makes winters the coldest in any major city in southeast Europe and the surrounding countries"},
{city:"Kiev",country:"Ukraine",fact:"archeological excavations have shown evidence of the first settlements in Kiev around 20,000 years ago"},
{city:"Stockholm",country:"Sweden",fact:"it\'s sometimes called ‘Venice of the North’ because of the beautiful architecture and open water"},
{city:"Edinburgh",country:"the UK",fact:"they hold the best New Years Eve party every year with over 100,000 people in the streets"},
  ],
};